In [ ]:
#importing
import numpy as np


In [ ]:
!pip install np


  Preparing metadata (setup.py) ... done
  Created wheel for np: filename=np-1.0.2-py3-none-any.whl size=13658 sha256=2546e878ea3d8e74e41f777866bb6ddab88676665567ad087556e2e5a119fa4f
  Stored in directory: /root/.cache/pip/wheels/f9/e1/79/c4580a03022dece233bc146286fc9082a8885ee1a7c8d8b980
Successfully built np


Arrays

In [ ]:
#creating 1D Array
a=np.array([4,5,6,7])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
#creating 2D Array (rows and columns)
b=np.array([[1,2,3],[2,3,4]])
print(b)

[[1 2 3]
 [2 3 4]]


In [ ]:
#creating 3D Array (rows,columns,groups)
c=np.array([[[2,3,4],[3,4,5]],[[4,5,6],[5,6,7]]])
print(c)

[[[2 3 4]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]]]


In [ ]:
#checking dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [ ]:
#ones
d=np.ones((2,3,3)) #groups,rows,colums #3D
print(d)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#ones
e=np.ones((3,2)) #rows,columns,2D
print(e)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#zeros
f=np.zeros((3,2)) #2D
print(f)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#identity matrix
j=np.eye(4)
print(j)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
h=np.eye(4,3)
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
#arange
i=np.arange(3,31,3) #start,stop,step
print(i)

[ 3  6  9 12 15 18 21 24 27 30]


In [ ]:
#arange with reshape(we can change into rows and columns with our specification)
i=np.arange(4,41,4).reshape(5,2)
print(i)

[[ 4  8]
 [12 16]
 [20 24]
 [28 32]
 [36 40]]


In [ ]:
#arange
i=np.arange(5,1001,5).reshape(50,4)
print(i)

[[   5   10   15   20]
 [  25   30   35   40]
 [  45   50   55   60]
 [  65   70   75   80]
 [  85   90   95  100]
 [ 105  110  115  120]
 [ 125  130  135  140]
 [ 145  150  155  160]
 [ 165  170  175  180]
 [ 185  190  195  200]
 [ 205  210  215  220]
 [ 225  230  235  240]
 [ 245  250  255  260]
 [ 265  270  275  280]
 [ 285  290  295  300]
 [ 305  310  315  320]
 [ 325  330  335  340]
 [ 345  350  355  360]
 [ 365  370  375  380]
 [ 385  390  395  400]
 [ 405  410  415  420]
 [ 425  430  435  440]
 [ 445  450  455  460]
 [ 465  470  475  480]
 [ 485  490  495  500]
 [ 505  510  515  520]
 [ 525  530  535  540]
 [ 545  550  555  560]
 [ 565  570  575  580]
 [ 585  590  595  600]
 [ 605  610  615  620]
 [ 625  630  635  640]
 [ 645  650  655  660]
 [ 665  670  675  680]
 [ 685  690  695  700]
 [ 705  710  715  720]
 [ 725  730  735  740]
 [ 745  750  755  760]
 [ 765  770  775  780]
 [ 785  790  795  800]
 [ 805  810  815  820]
 [ 825  830  835  840]
 [ 845  850  855  860]
 [ 865  870

In [ ]:
#linespace
j=np.linspace(27,29,10)
print(j)

[27.         27.22222222 27.44444444 27.66666667 27.88888889 28.11111111
 28.33333333 28.55555556 28.77777778 29.        ]


In [ ]:
j=np.linspace(1,2,6)
print(j)

[1.  1.2 1.4 1.6 1.8 2. ]


In [ ]:
[1.  1.2 1.4 1.6 1.8 2. ]


Operations

In [ ]:
import numpy as np
k=np.arange(2,8).reshape(3,2)
print(k)
m=np.arange(13,19).reshape(3,2)
print(m)
print(m+k)
print(m-k)
print(m*k)
print(m/k)

[[2 3]
 [4 5]
 [6 7]]
[[13 14]
 [15 16]
 [17 18]]
[[15 17]
 [19 21]
 [23 25]]
[[11 11]
 [11 11]
 [11 11]]
[[ 26  42]
 [ 60  80]
 [102 126]]
[[6.5        4.66666667]
 [3.75       3.2       ]
 [2.83333333 2.57142857]]


In [ ]:
n=np.sum(k*m)
print(n)

436


axis=0 => columns
axis=1 => rows
axis=2 => groups

In [ ]:
o=np.sum((k,m),axis=0)
print(o)

[[15 17]
 [19 21]
 [23 25]]


In [ ]:
o=np.sum((k,m),axis=1)
print(o)

[[12 15]
 [45 48]]


In [ ]:
o=np.sum((k,m),axis=2)
print(o)

[[ 5  9 13]
 [27 31 35]]


In [ ]:
h=np.ones((4,2))
g=np.ones((4,2))
print(np.sum((h,g),axis=0))
print(np.sum((h,g),axis=1))

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]
[[4. 4.]
 [4. 4.]]


In [ ]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])
print(a*b)
print(a@b)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


b=np.array[25,289,361,81] #find square roots and iterate through result values
output=5 square is 25

In [ ]:
b=np.array([25,289,361,81])
for i in b:
  print((np.sqrt(i)),"square is",i)

5.0 square is 25
17.0 square is 289
19.0 square is 361
9.0 square is 81


Array_joins

In [ ]:
a=np.array([23,24,25,26,27,28]).reshape(2,3)
b=np.array([4,5,6,7,8,9]).reshape(2,3)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[23 24 25]
 [26 27 28]
 [ 4  5  6]
 [ 7  8  9]]
[[23 24 25  4  5  6]
 [26 27 28  7  8  9]]


In [ ]:
a=np.array([23,24,25,26,27,28])
a.resize(2,3)
b=np.array([4,5,6,7,8,9])
b.resize(2,3)
print(np.vstack((a,b))) #columns
print(np.hstack((a,b))) #rows

[[23 24 25]
 [26 27 28]
 [ 4  5  6]
 [ 7  8  9]]
[[23 24 25  4  5  6]
 [26 27 28  7  8  9]]


In [ ]:
a=np.arange(30).reshape(2,3,5) #groups,rows,columns
print(a)
print("Output:")
print(np.dstack(a)) #no. of groups=2 => 2 columns in each group, no. of rows=3 => 3 groups formed

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
Output:
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]
