In [ ]:
import numpy as np

In [ ]:
a=np.ones((4,8))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


inside numpy random is subpackage
when we have to access subpackage we have to assign package name.subpackage
range of rand function is 0-1

In [ ]:
a=np.random.rand(1)
print(a)

[0.61416485]


In [ ]:
a=np.random.rand(8,4)       #to return 8 rows 4 columns
print(a)

[[0.93433303 0.53391377 0.21465164 0.86594388]
 [0.92321908 0.55346386 0.67062962 0.43202116]
 [0.15505824 0.19369611 0.62810361 0.83582954]
 [0.99448691 0.25201506 0.33671444 0.97520452]
 [0.67265109 0.62490786 0.08307684 0.89804854]
 [0.12199127 0.86296616 0.83391205 0.59343497]
 [0.31961844 0.89563866 0.99061707 0.01919016]
 [0.33937943 0.17872777 0.71091489 0.67995342]]


In [ ]:
a=10*np.random.rand(8,4) #returns values btw 0-10
print(a)

[[9.40697016 1.13512218 2.31711389 5.23188308]
 [3.68216483 3.74073377 0.06615358 2.81885886]
 [3.53912624 8.16258123 1.1067624  1.33469387]
 [4.51775803 2.51472768 9.07335807 8.33590053]
 [8.55439897 7.49695794 3.7650845  3.92876223]
 [1.49263432 0.98197754 2.36428093 2.14099368]
 [2.75462491 9.03773102 4.62109381 7.85427448]
 [1.59905541 6.99528344 6.29385853 4.3080128 ]]


In [ ]:
a=np.ceil(10*np.random.rand(8,4)) #floor=min value,ceil=max value
print(a)

[[ 9.  8. 10. 10.]
 [ 8.  4.  6.  9.]
 [10.  4.  2.  1.]
 [ 3.  7.  7.  7.]
 [ 8. 10.  6.  2.]
 [ 7.  8.  3.  5.]
 [ 8.  9.  8.  7.]
 [ 5.  2.  2.  9.]]


spliting is 2 types:
- vsplit:top to bottom
- hsplit:side by side

In [ ]:
A=np.arange(1,33).reshape(8,4) #for vertical split
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
np.vsplit(A,4) #4 will divide 8 so we are getting 2 rows each for 4 arrays

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(A,(3,4))  #split it after 3rd row and 4th row

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
B=np.arange(1,33).reshape(4,8) #for horizontal split
print(B)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(B,4)   #4 should divide 8 and we have 2 columns for 4 arrays

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(B,(3,4,5))  # split after 3rd column and 4th column and 5th column

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27]]),
 array([[ 4],
        [12],
        [20],
        [28]]),
 array([[ 5],
        [13],
        [21],
        [29]]),
 array([[ 6,  7,  8],
        [14, 15, 16],
        [22, 23, 24],
        [30, 31, 32]])]

Trigonometry



In [ ]:
np.pi

3.141592653589793

In [ ]:
a=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(a)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
b=np.rad2deg(a)      #convert radians to degree
print(b)

[ 45.  60.  90. 180.]


In [ ]:
c=[ 45.,  60.,  90., 180.]   #converts deg to radians
print(np.deg2rad(c))

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
a=np.sin(90)
print(a)
b=np.cos(0)
print(b)
c=np.tan(1)
print(c)

0.8939966636005579
1.0
1.5574077246549023


Statistics:
- mean: sum of observ/no. of observ
- median: after sorting the array middle value is median
- standard deviation: difference between n values and mean and sum them and divide the sum with n-1
- variance: sd**2

In [ ]:
ar=np.array([23,13,9,6,28,26])
a=np.mean(ar)
print(a)
b=np.median(ar)
print(b)
c=np.var(ar)
print(c)
d=np.std(ar)
print(d)

17.5
18.0
72.91666666666667
8.539125638299666


linalg is also subpackage in linalg we have inverse subpackage

In [ ]:
c=np.arange(1,5).reshape(2,2)
print(c)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(c)  #inverse of a matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
c=np.arange(1,25).reshape(6,4)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
print(np.argmax(c)) #argmax=returns index position of max value in the array

23


In [ ]:
d=np.floor(10*np.random.rand(24)).reshape(6,4)
print(d)

[[1. 0. 4. 7.]
 [6. 7. 7. 5.]
 [4. 7. 2. 9.]
 [7. 0. 9. 4.]
 [7. 7. 3. 7.]
 [1. 3. 2. 4.]]


In [ ]:
print(np.argmax(d))

11


In [ ]:
d=10*np.random.rand(24).reshape(6,4)
print(d)

[[2.77018345 8.49919484 2.11128424 3.55558174]
 [9.08639892 8.77191963 0.31168096 5.33982317]
 [4.11690054 6.34883831 2.51194345 8.0748807 ]
 [9.64406709 1.49927088 9.16440803 0.88408508]
 [6.7473124  3.36862755 3.23085361 7.77078445]
 [3.26114597 4.9444712  5.65359818 2.11846695]]


In [ ]:
print(np.argmax(d,axis=0)) #returns each column index position of max value

[3 1 3 2]


In [ ]:
print(np.argmax(d,axis=1))   #returns each row index position of max value

[1 0 3 0 3 2]


In [ ]:
print(np.argmin(d))          #returns min value in the array

6


In [ ]:
print(np.argmin(d,axis=0))

[0 3 1 3]


In [ ]:
print(np.argmin(d,axis=1))

[2 2 2 3 2 3]


Searching

In [ ]:
a=np.array([1,  2,  3,  4, 5,  6,  7,  8])
print(np.where(a%2==0))

(array([], dtype=int64),)


In [ ]:
a=np.array([24,16,7,17,54,60])
print(np.where(a%6==0))

(array([0, 4, 5]),)


In [ ]:
#used for only sorted array
a=np.array([1,2,3,7,8,9])
x=np.searchsorted(a,2)
print(x)

1


In [ ]:
a=np.array([24,16,7,17,54,60]) #not applicable for unsorted
x=np.searchsorted(a,17)   #7,16,17,24,54,60
print(x)

3


In [ ]:
#sorting array
a=np.array([24,16,7,17,54,60])                              #numerical,1D
d=np.array([[24,16,7],[17,54,60]])                          #2D
b=np.array(['apple','cherry','banana'])                     #string
c=np.array([True,True,False])                               #boolean
print(np.sort(a))
print(np.sort(b))
print(np.sort(c))
print(np.sort(d))

[ 7 16 17 24 54 60]
['apple' 'banana' 'cherry']
[False  True  True]
[[ 7 16 24]
 [17 54 60]]


Filter:

In [ ]:
a=np.array([40,43,40,44,67,78])
filt=np.where(a%2==0)
print(filt)

(array([0, 2, 3, 5]),)


In [ ]:
a[filt]

array([40, 40, 44, 78])

In [ ]:
#zip is used to join two arrays,lists
names=np.array(["jwalitha","vasavi","pavan","harsha"])
initials=np.array(["k","k","k","k"])
for i,j in zip(initials,names):
  print(i,".",j)

k . jwalitha
k . vasavi
k . pavan
k . harsha


In [ ]:
a=np.array([14,15,16,17,18])
b=np.array([25,26,27,28,29])
m=np.multiply(a,b)
print(m)
n=np.divide(a,b)
print(n)
o=np.mod(a,b)
print(o)
p=np.divmod(a,b)
print(p)

[350 390 432 476 522]
[0.56       0.57692308 0.59259259 0.60714286 0.62068966]
[14 15 16 17 18]
(array([0, 0, 0, 0, 0]), array([14, 15, 16, 17, 18]))


Logarithms

In [ ]:
a=np.arange(1,10)
print(a)
print(np.log2(a))        #log a base2
print(np.log10(a))       #log a base10
print(np.log(a))         #natural log a

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


CUMMULATIVE FUNCTIONS
- cummulative sum
- cummulative product

In [ ]:
a=np.array([13,14,15,16,17])
x=np.cumsum(a)
print(x)
y=np.cumprod(a)
print(y)

[13 27 42 58 75]
[    13    182   2730  43680 742560]


In [ ]:
#difference
a=np.array([20,13,45,60])      #e2-e1
x=np.diff(a)
print(x)

[-7 32 15]


In [ ]:
#lcm
a=455
b=665
x=np.lcm(a,b)
print(x)

8645


In [ ]:
#gcd
a=455
b=665
x=np.gcd(a,b)
print(x)

35


In [ ]:
#gcd
a=np.array([455,665])
x=np.gcd.reduce(a)       #reduce is used for taking multiple inputs and gives single output
print(x)


35


In [ ]:
#lcm
a=np.array([455,665])
x=np.lcm.reduce(a)       #reduce is used for taking multiple inputs and gives single output
print(x)


8645
